GET http://localhost:3000/inventory

################################

GET http://localhost:3000/inventory/60fe51fc631ff30b24d5e349

###

POST http://localhost:3000/inventory/
Content-Type: application/json

{
    "name" : "Amator",
    "wine":"RED",
    "year" : "2011",
    "origine": "Tirane"
}

#######
DELETE http://localhost:3000/inventory/60ff52a94bc38c3dc07ef5d6

#######

PATCH http://localhost:3000/inventory/60fe51e4631ff30b24d5e347
Content-Type: application/json

{
    "year" : 1234
}

##########

PUT http://localhost:3000/inventory/60ff62efdd6f6947109a83ee

{
    "name" : "Vodka",
    "wine" : "red",
    "year" : 2000,
    "origine" : "tiron"
}