GET http://localhost:3000/inventory

################################

GET http://localhost:3000/inventory/60ff8fb530aca20da48ed61e

###

POST http://localhost:3000/inventory/
Content-Type: application/json

{
    "name" : "Amator",
    "wine":"RED",
    "year" : 2011,
    "origine": "Tirane"
}

#######
DELETE http://localhost:3000/inventory/60ff9c42375d983e783b3a3b

#######

PATCH http://localhost:3000/inventory/60ff9c42375d983e783b3a3b
Content-Type: application/json

{
    "year" : 1234
}

##########
